spring:
  profiles:
    active: @env@
  application:
    name: springboot3-demo
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    servlet:
      load-on-startup: 0
    #出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  resources:
    #static-locations: classpath:/static/
  #  messages:
  #    basename: il8n/
  # activity 配置
  activiti:
    database-schema-update: false
    check-process-definitions: false
    process-definition-location-prefix: classpath:/processes/
    # history-level: full
    async-executor-activate: false
#  freemarker:
#    templateLoaderPath: classpath:/templates/
#    suffix: .ftl
#    charset: UTF-8
#    request-context-attribute: request
#    settings:
#      number_format: 0.##########
#      classic_compatible: true
management:
  health:
    # 关闭es检测
    elasticsearch:
      enabled: false
    # 关闭邮件启动检测
    mail:
      enabled: false
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml,classpath*:*mapper/**/*Mapper.xml,classpath*:*mapper/*Mapper.xml
  type-aliases-package: com.zenith.**.entity,com.zenith.core.**.entity,com.zenith.**.modal
  #typeEnumsPackage: org.springblade.dashboard.entity.enums
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      id-type: ID_WORKER
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      #驼峰下划线转换
      column-underline: true
      # 逻辑删除配置
      # 逻辑删除全局值（1表示已删除，Mybatis Plus的默认配置）
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除，Mybatis Plus的默认配置）
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
    call-setters-on-nulls: true